### ISSUE TITLE
Capitalize first letter of Risk Approach in tables and exports

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1549]
![image](https://user-images.githubusercontent.com/3675043/105741634-8aeb8500-5f08-11eb-94e9-eb9f64d35085.png)

![image](https://user-images.githubusercontent.com/3675043/105741645-90e16600-5f08-11eb-948d-ddcd24440209.png)

**Comment by juan-rivera-2020** [comment]
Done: 
![image](https://user-images.githubusercontent.com/72885316/108230928-402bea00-710f-11eb-9026-af8ad3e90d64.png)

**Comment by LAlexMHllc** [comment]
Still not done on Risk forms, Sheet table, Kanban cards, Map cards, and exports

**Comment by juan-rivera-2020** [comment]
These are from 9:22am QA deployment this morning:
**Map view:**
![image](https://user-images.githubusercontent.com/72885316/108423516-f4a83780-7205-11eb-982c-cd5cf59f2bd0.png)

**Sheet View:**
![image](https://user-images.githubusercontent.com/72885316/108423616-10abd900-7206-11eb-9420-2d8555b1b4f4.png)

It's capitalized in the Risk Form and Kanban cards as well.
